// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: mall-demo/micro-mall-member/proto/micro-mall-member-proto/member.proto

package proto_member

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SocialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *SocialRequest) Reset() {
	*x = SocialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialRequest) ProtoMessage() {}

func (x *SocialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialRequest.ProtoReflect.Descriptor instead.
func (*SocialRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{0}
}

func (x *SocialRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type SocialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
}

func (x *SocialResponse) Reset() {
	*x = SocialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialResponse) ProtoMessage() {}

func (x *SocialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialResponse.ProtoReflect.Descriptor instead.
func (*SocialResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{1}
}

func (x *SocialResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocialResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{3}
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username    string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{5}
}

type GetMemberListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNum  int32  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`    // 当前页码
	PageSize int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` //每页记录数
	Keyword  string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`                    //检索关键字
	Order    string `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`                        //排序方式
	Sidx     string `protobuf:"bytes,5,opt,name=sidx,proto3" json:"sidx,omitempty"`                          // 排序字段
}

func (x *GetMemberListRequest) Reset() {
	*x = GetMemberListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemberListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberListRequest) ProtoMessage() {}

func (x *GetMemberListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberListRequest.ProtoReflect.Descriptor instead.
func (*GetMemberListRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{6}
}

func (x *GetMemberListRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetMemberListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMemberListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetMemberListRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *GetMemberListRequest) GetSidx() string {
	if x != nil {
		return x.Sidx
	}
	return ""
}

type MemberEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                    // id
	LevelId     int64  `protobuf:"varint,2,opt,name=level_id,json=levelId,proto3" json:"level_id,omitempty"`           // 会员等级ID
	UserName    string `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`         // 用户名
	Password    string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`                         // 密码
	Nickname    string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`                         // 昵称
	Mobile      string `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`                             // 手机号码
	Email       string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`                               // 邮箱
	Header      string `protobuf:"bytes,8,opt,name=header,proto3" json:"header,omitempty"`                             // 头像
	Gender      int32  `protobuf:"varint,9,opt,name=gender,proto3" json:"gender,omitempty"`                            // 性别
	Birth       string `protobuf:"bytes,10,opt,name=birth,proto3" json:"birth,omitempty"`                              // 生日
	City        string `protobuf:"bytes,11,opt,name=city,proto3" json:"city,omitempty"`                                // 所在城市
	Job         string `protobuf:"bytes,12,opt,name=job,proto3" json:"job,omitempty"`                                  // 职业
	Sign        string `protobuf:"bytes,13,opt,name=sign,proto3" json:"sign,omitempty"`                                // 个性签名
	SourceType  int32  `protobuf:"varint,14,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // 用户来源
	Integration int32  `protobuf:"varint,15,opt,name=integration,proto3" json:"integration,omitempty"`                 // 积分
	Growth      int32  `protobuf:"varint,16,opt,name=growth,proto3" json:"growth,omitempty"`                           // 成长值
	Status      int32  `protobuf:"varint,17,opt,name=status,proto3" json:"status,omitempty"`                           // 启用状态
}

func (x *MemberEntity) Reset() {
	*x = MemberEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberEntity) ProtoMessage() {}

func (x *MemberEntity) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberEntity.ProtoReflect.Descriptor instead.
func (*MemberEntity) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{7}
}

func (x *MemberEntity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberEntity) GetLevelId() int64 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *MemberEntity) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MemberEntity) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MemberEntity) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *MemberEntity) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *MemberEntity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MemberEntity) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *MemberEntity) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *MemberEntity) GetBirth() string {
	if x != nil {
		return x.Birth
	}
	return ""
}

func (x *MemberEntity) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *MemberEntity) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *MemberEntity) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *MemberEntity) GetSourceType() int32 {
	if x != nil {
		return x.SourceType
	}
	return 0
}

func (x *MemberEntity) GetIntegration() int32 {
	if x != nil {
		return x.Integration
	}
	return 0
}

func (x *MemberEntity) GetGrowth() int32 {
	if x != nil {
		return x.Growth
	}
	return 0
}

func (x *MemberEntity) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetMemberListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount     int32           `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PageSize       int32           `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPage      int32           `protobuf:"varint,3,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	CurrPage       int32           `protobuf:"varint,4,opt,name=curr_page,json=currPage,proto3" json:"curr_page,omitempty"`
	MemberEntities []*MemberEntity `protobuf:"bytes,5,rep,name=member_entities,json=memberEntities,proto3" json:"member_entities,omitempty"`
}

func (x *GetMemberListResponse) Reset() {
	*x = GetMemberListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemberListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberListResponse) ProtoMessage() {}

func (x *GetMemberListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberListResponse.ProtoReflect.Descriptor instead.
func (*GetMemberListResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{8}
}

func (x *GetMemberListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetMemberListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMemberListResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *GetMemberListResponse) GetCurrPage() int32 {
	if x != nil {
		return x.CurrPage
	}
	return 0
}

func (x *GetMemberListResponse) GetMemberEntities() []*MemberEntity {
	if x != nil {
		return x.MemberEntities
	}
	return nil
}

type SaveMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberEntity *MemberEntity `protobuf:"bytes,1,opt,name=member_entity,json=memberEntity,proto3" json:"member_entity,omitempty"`
}

func (x *SaveMemberRequest) Reset() {
	*x = SaveMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemberRequest) ProtoMessage() {}

func (x *SaveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemberRequest.ProtoReflect.Descriptor instead.
func (*SaveMemberRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{9}
}

func (x *SaveMemberRequest) GetMemberEntity() *MemberEntity {
	if x != nil {
		return x.MemberEntity
	}
	return nil
}

type SaveMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveMemberResponse) Reset() {
	*x = SaveMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemberResponse) ProtoMessage() {}

func (x *SaveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemberResponse.ProtoReflect.Descriptor instead.
func (*SaveMemberResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{10}
}

type UpdateMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberEntity *MemberEntity `protobuf:"bytes,1,opt,name=member_entity,json=memberEntity,proto3" json:"member_entity,omitempty"`
}

func (x *UpdateMemberRequest) Reset() {
	*x = UpdateMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRequest) ProtoMessage() {}

func (x *UpdateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMemberRequest) GetMemberEntity() *MemberEntity {
	if x != nil {
		return x.MemberEntity
	}
	return nil
}

type UpdateMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMemberResponse) Reset() {
	*x = UpdateMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberResponse) ProtoMessage() {}

func (x *UpdateMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemberResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{12}
}

type DeleteMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *DeleteMemberRequest) Reset() {
	*x = DeleteMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberRequest) ProtoMessage() {}

func (x *DeleteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemberRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteMemberRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMemberResponse) Reset() {
	*x = DeleteMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberResponse) ProtoMessage() {}

func (x *DeleteMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemberResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{14}
}

type SaveMemberLevelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberLevelEntity *MemberLevelEntity `protobuf:"bytes,1,opt,name=member_level_entity,json=memberLevelEntity,proto3" json:"member_level_entity,omitempty"`
}

func (x *SaveMemberLevelRequest) Reset() {
	*x = SaveMemberLevelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMemberLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemberLevelRequest) ProtoMessage() {}

func (x *SaveMemberLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemberLevelRequest.ProtoReflect.Descriptor instead.
func (*SaveMemberLevelRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{15}
}

func (x *SaveMemberLevelRequest) GetMemberLevelEntity() *MemberLevelEntity {
	if x != nil {
		return x.MemberLevelEntity
	}
	return nil
}

type SaveMemberLevelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveMemberLevelResponse) Reset() {
	*x = SaveMemberLevelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMemberLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemberLevelResponse) ProtoMessage() {}

func (x *SaveMemberLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemberLevelResponse.ProtoReflect.Descriptor instead.
func (*SaveMemberLevelResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{16}
}

type UpdateMemberLevelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberLevelEntity *MemberLevelEntity `protobuf:"bytes,1,opt,name=member_level_entity,json=memberLevelEntity,proto3" json:"member_level_entity,omitempty"`
}

func (x *UpdateMemberLevelRequest) Reset() {
	*x = UpdateMemberLevelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMemberLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberLevelRequest) ProtoMessage() {}

func (x *UpdateMemberLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberLevelRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberLevelRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateMemberLevelRequest) GetMemberLevelEntity() *MemberLevelEntity {
	if x != nil {
		return x.MemberLevelEntity
	}
	return nil
}

type UpdateMemberLevelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMemberLevelResponse) Reset() {
	*x = UpdateMemberLevelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMemberLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberLevelResponse) ProtoMessage() {}

func (x *UpdateMemberLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberLevelResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemberLevelResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{18}
}

type DeleteMemberLevelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *DeleteMemberLevelRequest) Reset() {
	*x = DeleteMemberLevelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMemberLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberLevelRequest) ProtoMessage() {}

func (x *DeleteMemberLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberLevelRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemberLevelRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteMemberLevelRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteMemberLevelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMemberLevelResponse) Reset() {
	*x = DeleteMemberLevelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMemberLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberLevelResponse) ProtoMessage() {}

func (x *DeleteMemberLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberLevelResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemberLevelResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{20}
}

type GetMemberLevelListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNum  int32  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`    // 当前页码
	PageSize int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` //每页记录数
	Keyword  string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`                    //检索关键字
	Order    string `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`                        //排序方式
	Sidx     string `protobuf:"bytes,5,opt,name=sidx,proto3" json:"sidx,omitempty"`                          // 排序字段
}

func (x *GetMemberLevelListRequest) Reset() {
	*x = GetMemberLevelListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemberLevelListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberLevelListRequest) ProtoMessage() {}

func (x *GetMemberLevelListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberLevelListRequest.ProtoReflect.Descriptor instead.
func (*GetMemberLevelListRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{21}
}

func (x *GetMemberLevelListRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetMemberLevelListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMemberLevelListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetMemberLevelListRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *GetMemberLevelListRequest) GetSidx() string {
	if x != nil {
		return x.Sidx
	}
	return ""
}

type MemberLevelEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                    int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GrowthPoint           int32   `protobuf:"varint,3,opt,name=growth_point,json=growthPoint,proto3" json:"growth_point,omitempty"`
	DefaultStatus         int32   `protobuf:"varint,4,opt,name=default_status,json=defaultStatus,proto3" json:"default_status,omitempty"`
	FreeFreightPoint      float32 `protobuf:"fixed32,5,opt,name=free_freight_point,json=freeFreightPoint,proto3" json:"free_freight_point,omitempty"`
	CommentGrowthPoint    int32   `protobuf:"varint,6,opt,name=comment_growth_point,json=commentGrowthPoint,proto3" json:"comment_growth_point,omitempty"`
	PriviledgeFreeFreight int32   `protobuf:"varint,7,opt,name=priviledge_free_freight,json=priviledgeFreeFreight,proto3" json:"priviledge_free_freight,omitempty"`
	PriviledgeMemberPrice int32   `protobuf:"varint,8,opt,name=priviledge_member_price,json=priviledgeMemberPrice,proto3" json:"priviledge_member_price,omitempty"`
	PriviledgeBirthday    int32   `protobuf:"varint,9,opt,name=priviledge_birthday,json=priviledgeBirthday,proto3" json:"priviledge_birthday,omitempty"`
	Note                  string  `protobuf:"bytes,10,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *MemberLevelEntity) Reset() {
	*x = MemberLevelEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberLevelEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberLevelEntity) ProtoMessage() {}

func (x *MemberLevelEntity) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberLevelEntity.ProtoReflect.Descriptor instead.
func (*MemberLevelEntity) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{22}
}

func (x *MemberLevelEntity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberLevelEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberLevelEntity) GetGrowthPoint() int32 {
	if x != nil {
		return x.GrowthPoint
	}
	return 0
}

func (x *MemberLevelEntity) GetDefaultStatus() int32 {
	if x != nil {
		return x.DefaultStatus
	}
	return 0
}

func (x *MemberLevelEntity) GetFreeFreightPoint() float32 {
	if x != nil {
		return x.FreeFreightPoint
	}
	return 0
}

func (x *MemberLevelEntity) GetCommentGrowthPoint() int32 {
	if x != nil {
		return x.CommentGrowthPoint
	}
	return 0
}

func (x *MemberLevelEntity) GetPriviledgeFreeFreight() int32 {
	if x != nil {
		return x.PriviledgeFreeFreight
	}
	return 0
}

func (x *MemberLevelEntity) GetPriviledgeMemberPrice() int32 {
	if x != nil {
		return x.PriviledgeMemberPrice
	}
	return 0
}

func (x *MemberLevelEntity) GetPriviledgeBirthday() int32 {
	if x != nil {
		return x.PriviledgeBirthday
	}
	return 0
}

func (x *MemberLevelEntity) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type GetMemberLevelListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount          int32                `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PageSize            int32                `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPage           int32                `protobuf:"varint,3,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	CurrPage            int32                `protobuf:"varint,4,opt,name=curr_page,json=currPage,proto3" json:"curr_page,omitempty"`
	MemberLevelEntities []*MemberLevelEntity `protobuf:"bytes,5,rep,name=member_level_entities,json=memberLevelEntities,proto3" json:"member_level_entities,omitempty"`
}

func (x *GetMemberLevelListResponse) Reset() {
	*x = GetMemberLevelListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemberLevelListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberLevelListResponse) ProtoMessage() {}

func (x *GetMemberLevelListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberLevelListResponse.ProtoReflect.Descriptor instead.
func (*GetMemberLevelListResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP(), []int{23}
}

func (x *GetMemberLevelListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetMemberLevelListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMemberLevelListResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *GetMemberLevelListResponse) GetCurrPage() int32 {
	if x != nil {
		return x.CurrPage
	}
	return 0
}

func (x *GetMemberLevelListResponse) GetMemberLevelEntities() []*MemberLevelEntity {
	if x != nil {
		return x.MemberLevelEntities
	}
	return nil
}

var File_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto protoreflect.FileDescriptor

var file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDesc = []byte{
	0x0a, 0x46, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2d, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2d, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x32, 0x0a, 0x0d, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x3d, 0x0a, 0x0e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x46, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6c, 0x0a, 0x0f, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x92, 0x01,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75,
	0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x64, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69,
	0x64, 0x78, 0x22, 0xaf, 0x03, 0x0a, 0x0c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x62, 0x69, 0x72, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6a,
	0x6f, 0x62, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67,
	0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x11, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0xcf, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x75, 0x72, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x63, 0x75, 0x72, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x3c, 0x0a, 0x0f, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x11, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0d, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4f, 0x0a, 0x13, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x38, 0x0a, 0x0d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0c,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x16, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x16, 0x0a,
	0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x62, 0x0a, 0x16, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x48, 0x0a, 0x13, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x11, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x61, 0x76,
	0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x64, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x48, 0x0a, 0x13, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x11, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x1b, 0x0a, 0x19, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2c, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x1b, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x78,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x64, 0x78, 0x22, 0x96, 0x03, 0x0a,
	0x11, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x72, 0x6f, 0x77, 0x74, 0x68,
	0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x67, 0x72,
	0x6f, 0x77, 0x74, 0x68, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x2c, 0x0a, 0x12, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x66, 0x72, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x66, 0x72,
	0x65, 0x65, 0x46, 0x72, 0x65, 0x69, 0x67, 0x68, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x30,
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x67, 0x72, 0x6f, 0x77, 0x74, 0x68,
	0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x36, 0x0a, 0x17, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x66,
	0x72, 0x65, 0x65, 0x5f, 0x66, 0x72, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x15, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x46, 0x72, 0x65,
	0x65, 0x46, 0x72, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x36, 0x0a, 0x17, 0x70, 0x72, 0x69, 0x76,
	0x69, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x70, 0x72, 0x69, 0x76, 0x69,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x2f, 0x0a, 0x13, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x62,
	0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x70,
	0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0xe4, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x4c,
	0x0a, 0x15, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x13, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x32, 0xb6, 0x06, 0x0a,
	0x09, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x70, 0x63, 0x12, 0x59, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x56, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x53, 0x6f, 0x63,
	0x69, 0x61, 0x6c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescOnce sync.Once
	file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescData = file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDesc
)

func file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescGZIP() []byte {
	file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescOnce.Do(func() {
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescData = protoimpl.X.CompressGZIP(file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescData)
	})
	return file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDescData
}

var file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_goTypes = []interface{}{
	(*SocialRequest)(nil),              // 0: proto.SocialRequest
	(*SocialResponse)(nil),             // 1: proto.SocialResponse
	(*LoginRequest)(nil),               // 2: proto.LoginRequest
	(*LoginResponse)(nil),              // 3: proto.LoginResponse
	(*RegisterRequest)(nil),            // 4: proto.RegisterRequest
	(*RegisterResponse)(nil),           // 5: proto.RegisterResponse
	(*GetMemberListRequest)(nil),       // 6: proto.GetMemberListRequest
	(*MemberEntity)(nil),               // 7: proto.MemberEntity
	(*GetMemberListResponse)(nil),      // 8: proto.GetMemberListResponse
	(*SaveMemberRequest)(nil),          // 9: proto.SaveMemberRequest
	(*SaveMemberResponse)(nil),         // 10: proto.SaveMemberResponse
	(*UpdateMemberRequest)(nil),        // 11: proto.UpdateMemberRequest
	(*UpdateMemberResponse)(nil),       // 12: proto.UpdateMemberResponse
	(*DeleteMemberRequest)(nil),        // 13: proto.DeleteMemberRequest
	(*DeleteMemberResponse)(nil),       // 14: proto.DeleteMemberResponse
	(*SaveMemberLevelRequest)(nil),     // 15: proto.SaveMemberLevelRequest
	(*SaveMemberLevelResponse)(nil),    // 16: proto.SaveMemberLevelResponse
	(*UpdateMemberLevelRequest)(nil),   // 17: proto.UpdateMemberLevelRequest
	(*UpdateMemberLevelResponse)(nil),  // 18: proto.UpdateMemberLevelResponse
	(*DeleteMemberLevelRequest)(nil),   // 19: proto.DeleteMemberLevelRequest
	(*DeleteMemberLevelResponse)(nil),  // 20: proto.DeleteMemberLevelResponse
	(*GetMemberLevelListRequest)(nil),  // 21: proto.GetMemberLevelListRequest
	(*MemberLevelEntity)(nil),          // 22: proto.MemberLevelEntity
	(*GetMemberLevelListResponse)(nil), // 23: proto.GetMemberLevelListResponse
}
var file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_depIdxs = []int32{
	7,  // 0: proto.GetMemberListResponse.member_entities:type_name -> proto.MemberEntity
	7,  // 1: proto.SaveMemberRequest.member_entity:type_name -> proto.MemberEntity
	7,  // 2: proto.UpdateMemberRequest.member_entity:type_name -> proto.MemberEntity
	22, // 3: proto.SaveMemberLevelRequest.member_level_entity:type_name -> proto.MemberLevelEntity
	22, // 4: proto.UpdateMemberLevelRequest.member_level_entity:type_name -> proto.MemberLevelEntity
	22, // 5: proto.GetMemberLevelListResponse.member_level_entities:type_name -> proto.MemberLevelEntity
	21, // 6: proto.MemberRpc.GetMemberLevelList:input_type -> proto.GetMemberLevelListRequest
	15, // 7: proto.MemberRpc.SaveMemberLevel:input_type -> proto.SaveMemberLevelRequest
	17, // 8: proto.MemberRpc.UpdateMemberLevel:input_type -> proto.UpdateMemberLevelRequest
	19, // 9: proto.MemberRpc.DeleteMemberLevel:input_type -> proto.DeleteMemberLevelRequest
	6,  // 10: proto.MemberRpc.GetMemberList:input_type -> proto.GetMemberListRequest
	9,  // 11: proto.MemberRpc.SaveMember:input_type -> proto.SaveMemberRequest
	11, // 12: proto.MemberRpc.UpdateMember:input_type -> proto.UpdateMemberRequest
	13, // 13: proto.MemberRpc.DeleteMember:input_type -> proto.DeleteMemberRequest
	4,  // 14: proto.MemberRpc.Register:input_type -> proto.RegisterRequest
	2,  // 15: proto.MemberRpc.Login:input_type -> proto.LoginRequest
	0,  // 16: proto.MemberRpc.SocialLogin:input_type -> proto.SocialRequest
	23, // 17: proto.MemberRpc.GetMemberLevelList:output_type -> proto.GetMemberLevelListResponse
	16, // 18: proto.MemberRpc.SaveMemberLevel:output_type -> proto.SaveMemberLevelResponse
	18, // 19: proto.MemberRpc.UpdateMemberLevel:output_type -> proto.UpdateMemberLevelResponse
	20, // 20: proto.MemberRpc.DeleteMemberLevel:output_type -> proto.DeleteMemberLevelResponse
	8,  // 21: proto.MemberRpc.GetMemberList:output_type -> proto.GetMemberListResponse
	10, // 22: proto.MemberRpc.SaveMember:output_type -> proto.SaveMemberResponse
	12, // 23: proto.MemberRpc.UpdateMember:output_type -> proto.UpdateMemberResponse
	14, // 24: proto.MemberRpc.DeleteMember:output_type -> proto.DeleteMemberResponse
	5,  // 25: proto.MemberRpc.Register:output_type -> proto.RegisterResponse
	3,  // 26: proto.MemberRpc.Login:output_type -> proto.LoginResponse
	1,  // 27: proto.MemberRpc.SocialLogin:output_type -> proto.SocialResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_init() }
func file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_init() {
	if File_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemberListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemberListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveMemberLevelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveMemberLevelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMemberLevelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMemberLevelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMemberLevelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMemberLevelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemberLevelListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberLevelEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemberLevelListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_goTypes,
		DependencyIndexes: file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_depIdxs,
		MessageInfos:      file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_msgTypes,
	}.Build()
	File_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto = out.File
	file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_rawDesc = nil
	file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_goTypes = nil
	file_mall_demo_micro_mall_member_proto_micro_mall_member_proto_member_proto_depIdxs = nil
}
