// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: mall-demo/micro-mall-product/proto/micro-mall-coupon-proto/spu.proto

package proto_coupon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberPriceEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SkuId           int64   `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	MemberLevelId   int64   `protobuf:"varint,3,opt,name=member_level_id,json=memberLevelId,proto3" json:"member_level_id,omitempty"`
	MemberLevelName string  `protobuf:"bytes,4,opt,name=member_level_name,json=memberLevelName,proto3" json:"member_level_name,omitempty"`
	MemberPrice     float64 `protobuf:"fixed64,5,opt,name=member_price,json=memberPrice,proto3" json:"member_price,omitempty"`
	AddOther        int32   `protobuf:"varint,6,opt,name=add_other,json=addOther,proto3" json:"add_other,omitempty"`
}

func (x *MemberPriceEntity) Reset() {
	*x = MemberPriceEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberPriceEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberPriceEntity) ProtoMessage() {}

func (x *MemberPriceEntity) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberPriceEntity.ProtoReflect.Descriptor instead.
func (*MemberPriceEntity) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescGZIP(), []int{0}
}

func (x *MemberPriceEntity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberPriceEntity) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *MemberPriceEntity) GetMemberLevelId() int64 {
	if x != nil {
		return x.MemberLevelId
	}
	return 0
}

func (x *MemberPriceEntity) GetMemberLevelName() string {
	if x != nil {
		return x.MemberLevelName
	}
	return ""
}

func (x *MemberPriceEntity) GetMemberPrice() float64 {
	if x != nil {
		return x.MemberPrice
	}
	return 0
}

func (x *MemberPriceEntity) GetAddOther() int32 {
	if x != nil {
		return x.AddOther
	}
	return 0
}

type SpuBoundEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SpuId      int64   `protobuf:"varint,2,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	GrowBounds float64 `protobuf:"fixed64,3,opt,name=grow_bounds,json=growBounds,proto3" json:"grow_bounds,omitempty"`
	BuyBounds  float64 `protobuf:"fixed64,4,opt,name=buy_bounds,json=buyBounds,proto3" json:"buy_bounds,omitempty"`
	Work       int32   `protobuf:"varint,5,opt,name=work,proto3" json:"work,omitempty"`
}

func (x *SpuBoundEntity) Reset() {
	*x = SpuBoundEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpuBoundEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpuBoundEntity) ProtoMessage() {}

func (x *SpuBoundEntity) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpuBoundEntity.ProtoReflect.Descriptor instead.
func (*SpuBoundEntity) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescGZIP(), []int{1}
}

func (x *SpuBoundEntity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpuBoundEntity) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *SpuBoundEntity) GetGrowBounds() float64 {
	if x != nil {
		return x.GrowBounds
	}
	return 0
}

func (x *SpuBoundEntity) GetBuyBounds() float64 {
	if x != nil {
		return x.BuyBounds
	}
	return 0
}

func (x *SpuBoundEntity) GetWork() int32 {
	if x != nil {
		return x.Work
	}
	return 0
}

type SkuFullReductionEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SkuId       int64   `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	FullPrice   float64 `protobuf:"fixed64,3,opt,name=full_price,json=fullPrice,proto3" json:"full_price,omitempty"`
	ReducePrice float64 `protobuf:"fixed64,4,opt,name=reduce_price,json=reducePrice,proto3" json:"reduce_price,omitempty"`
	AddOther    int32   `protobuf:"varint,5,opt,name=add_other,json=addOther,proto3" json:"add_other,omitempty"`
}

func (x *SkuFullReductionEntity) Reset() {
	*x = SkuFullReductionEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuFullReductionEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuFullReductionEntity) ProtoMessage() {}

func (x *SkuFullReductionEntity) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuFullReductionEntity.ProtoReflect.Descriptor instead.
func (*SkuFullReductionEntity) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescGZIP(), []int{2}
}

func (x *SkuFullReductionEntity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SkuFullReductionEntity) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *SkuFullReductionEntity) GetFullPrice() float64 {
	if x != nil {
		return x.FullPrice
	}
	return 0
}

func (x *SkuFullReductionEntity) GetReducePrice() float64 {
	if x != nil {
		return x.ReducePrice
	}
	return 0
}

func (x *SkuFullReductionEntity) GetAddOther() int32 {
	if x != nil {
		return x.AddOther
	}
	return 0
}

type SkuLadderEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SkuId     int64   `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	FullCount int32   `protobuf:"varint,3,opt,name=full_count,json=fullCount,proto3" json:"full_count,omitempty"`
	Discount  float64 `protobuf:"fixed64,4,opt,name=discount,proto3" json:"discount,omitempty"`
	Price     float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	AddOther  int32   `protobuf:"varint,6,opt,name=add_other,json=addOther,proto3" json:"add_other,omitempty"`
}

func (x *SkuLadderEntity) Reset() {
	*x = SkuLadderEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuLadderEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuLadderEntity) ProtoMessage() {}

func (x *SkuLadderEntity) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuLadderEntity.ProtoReflect.Descriptor instead.
func (*SkuLadderEntity) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescGZIP(), []int{3}
}

func (x *SkuLadderEntity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SkuLadderEntity) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *SkuLadderEntity) GetFullCount() int32 {
	if x != nil {
		return x.FullCount
	}
	return 0
}

func (x *SkuLadderEntity) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *SkuLadderEntity) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SkuLadderEntity) GetAddOther() int32 {
	if x != nil {
		return x.AddOther
	}
	return 0
}

type SaveSkuLadderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuLadderEntities []*SkuLadderEntity `protobuf:"bytes,1,rep,name=sku_ladder_entities,json=skuLadderEntities,proto3" json:"sku_ladder_entities,omitempty"`
}

func (x *SaveSkuLadderRequest) Reset() {
	*x = SaveSkuLadderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSkuLadderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSkuLadderRequest) ProtoMessage() {}

func (x *SaveSkuLadderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSkuLadderRequest.ProtoReflect.Descriptor instead.
func (*SaveSkuLadderRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescGZIP(), []int{4}
}

func (x *SaveSkuLadderRequest) GetSkuLadderEntities() []*SkuLadderEntity {
	if x != nil {
		return x.SkuLadderEntities
	}
	return nil
}

type SaveSkuLadderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveSkuLadderResponse) Reset() {
	*x = SaveSkuLadderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSkuLadderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSkuLadderResponse) ProtoMessage() {}

func (x *SaveSkuLadderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSkuLadderResponse.ProtoReflect.Descriptor instead.
func (*SaveSkuLadderResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescGZIP(), []int{5}
}

type SaveSkuFullReductionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuFullReductionEntities []*SkuFullReductionEntity `protobuf:"bytes,1,rep,name=sku_full_reduction_entities,json=skuFullReductionEntities,proto3" json:"sku_full_reduction_entities,omitempty"`
}

func (x *SaveSkuFullReductionRequest) Reset() {
	*x = SaveSkuFullReductionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSkuFullReductionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSkuFullReductionRequest) ProtoMessage() {}

func (x *SaveSkuFullReductionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSkuFullReductionRequest.ProtoReflect.Descriptor instead.
func (*SaveSkuFullReductionRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescGZIP(), []int{6}
}

func (x *SaveSkuFullReductionRequest) GetSkuFullReductionEntities() []*SkuFullReductionEntity {
	if x != nil {
		return x.SkuFullReductionEntities
	}
	return nil
}

type SaveSkuFullReductionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveSkuFullReductionResponse) Reset() {
	*x = SaveSkuFullReductionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSkuFullReductionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSkuFullReductionResponse) ProtoMessage() {}

func (x *SaveSkuFullReductionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSkuFullReductionResponse.ProtoReflect.Descriptor instead.
func (*SaveSkuFullReductionResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescGZIP(), []int{7}
}

type SaveSpuBoundsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuBoundEntities *SpuBoundEntity `protobuf:"bytes,1,opt,name=spu_bound_entities,json=spuBoundEntities,proto3" json:"spu_bound_entities,omitempty"`
}

func (x *SaveSpuBoundsRequest) Reset() {
	*x = SaveSpuBoundsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSpuBoundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSpuBoundsRequest) ProtoMessage() {}

func (x *SaveSpuBoundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSpuBoundsRequest.ProtoReflect.Descriptor instead.
func (*SaveSpuBoundsRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescGZIP(), []int{8}
}

func (x *SaveSpuBoundsRequest) GetSpuBoundEntities() *SpuBoundEntity {
	if x != nil {
		return x.SpuBoundEntities
	}
	return nil
}

type SaveSpuboundsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveSpuboundsResponse) Reset() {
	*x = SaveSpuboundsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSpuboundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSpuboundsResponse) ProtoMessage() {}

func (x *SaveSpuboundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSpuboundsResponse.ProtoReflect.Descriptor instead.
func (*SaveSpuboundsResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescGZIP(), []int{9}
}

type SaveMemberPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberPriceEntities []*MemberPriceEntity `protobuf:"bytes,1,rep,name=member_price_entities,json=memberPriceEntities,proto3" json:"member_price_entities,omitempty"`
}

func (x *SaveMemberPriceRequest) Reset() {
	*x = SaveMemberPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMemberPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemberPriceRequest) ProtoMessage() {}

func (x *SaveMemberPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemberPriceRequest.ProtoReflect.Descriptor instead.
func (*SaveMemberPriceRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescGZIP(), []int{10}
}

func (x *SaveMemberPriceRequest) GetMemberPriceEntities() []*MemberPriceEntity {
	if x != nil {
		return x.MemberPriceEntities
	}
	return nil
}

type SaveMemberPriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveMemberPriceResponse) Reset() {
	*x = SaveMemberPriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMemberPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemberPriceResponse) ProtoMessage() {}

func (x *SaveMemberPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemberPriceResponse.ProtoReflect.Descriptor instead.
func (*SaveMemberPriceResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescGZIP(), []int{11}
}

var File_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto protoreflect.FileDescriptor

var file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDesc = []byte{
	0x0a, 0x44, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2d, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2d, 0x6d, 0x61, 0x6c, 0x6c, 0x2d,
	0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x75,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x70,
	0x75, 0x22, 0xce, 0x01, 0x0a, 0x11, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x6b, 0x75, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x6b, 0x75, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x5f, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x64, 0x64, 0x4f, 0x74, 0x68,
	0x65, 0x72, 0x22, 0x8b, 0x01, 0x0a, 0x0e, 0x53, 0x70, 0x75, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x70, 0x75, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x67, 0x72, 0x6f, 0x77, 0x5f, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0a, 0x67, 0x72, 0x6f, 0x77, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x75, 0x79, 0x5f, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x09, 0x62, 0x75, 0x79, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x77, 0x6f, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x6b,
	0x22, 0x9e, 0x01, 0x0a, 0x16, 0x53, 0x6b, 0x75, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73,
	0x6b, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x6b, 0x75,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x5f, 0x6f, 0x74, 0x68, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x64, 0x64, 0x4f, 0x74, 0x68, 0x65,
	0x72, 0x22, 0xa6, 0x01, 0x0a, 0x0f, 0x53, 0x6b, 0x75, 0x4c, 0x61, 0x64, 0x64, 0x65, 0x72, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x6b, 0x75, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x61, 0x64, 0x64, 0x5f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x61, 0x64, 0x64, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x22, 0x62, 0x0a, 0x14, 0x53, 0x61,
	0x76, 0x65, 0x53, 0x6b, 0x75, 0x4c, 0x61, 0x64, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x4a, 0x0a, 0x13, 0x73, 0x6b, 0x75, 0x5f, 0x6c, 0x61, 0x64, 0x64, 0x65, 0x72,
	0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x70, 0x75, 0x2e, 0x53, 0x6b, 0x75, 0x4c,
	0x61, 0x64, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x11, 0x73, 0x6b, 0x75,
	0x4c, 0x61, 0x64, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x17,
	0x0a, 0x15, 0x53, 0x61, 0x76, 0x65, 0x53, 0x6b, 0x75, 0x4c, 0x61, 0x64, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7f, 0x0a, 0x1b, 0x53, 0x61, 0x76, 0x65, 0x53,
	0x6b, 0x75, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x60, 0x0a, 0x1b, 0x73, 0x6b, 0x75, 0x5f, 0x66, 0x75,
	0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x70, 0x75, 0x2e, 0x53, 0x6b, 0x75, 0x46, 0x75, 0x6c, 0x6c, 0x52,
	0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x18,
	0x73, 0x6b, 0x75, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x1e, 0x0a, 0x1c, 0x53, 0x61, 0x76, 0x65,
	0x53, 0x6b, 0x75, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5f, 0x0a, 0x14, 0x53, 0x61, 0x76, 0x65,
	0x53, 0x70, 0x75, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x47, 0x0a, 0x12, 0x73, 0x70, 0x75, 0x5f, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x70, 0x75, 0x2e, 0x53, 0x70, 0x75, 0x42, 0x6f, 0x75, 0x6e,
	0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x10, 0x73, 0x70, 0x75, 0x42, 0x6f, 0x75, 0x6e,
	0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x61, 0x76,
	0x65, 0x53, 0x70, 0x75, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x6a, 0x0a, 0x16, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x50, 0x0a, 0x15,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x70, 0x75, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x13, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x50, 0x72, 0x69, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x19,
	0x0a, 0x17, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescOnce sync.Once
	file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescData = file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDesc
)

func file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescGZIP() []byte {
	file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescOnce.Do(func() {
		file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescData = protoimpl.X.CompressGZIP(file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescData)
	})
	return file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDescData
}

var file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_goTypes = []interface{}{
	(*MemberPriceEntity)(nil),            // 0: proto_spu.MemberPriceEntity
	(*SpuBoundEntity)(nil),               // 1: proto_spu.SpuBoundEntity
	(*SkuFullReductionEntity)(nil),       // 2: proto_spu.SkuFullReductionEntity
	(*SkuLadderEntity)(nil),              // 3: proto_spu.SkuLadderEntity
	(*SaveSkuLadderRequest)(nil),         // 4: proto_spu.SaveSkuLadderRequest
	(*SaveSkuLadderResponse)(nil),        // 5: proto_spu.SaveSkuLadderResponse
	(*SaveSkuFullReductionRequest)(nil),  // 6: proto_spu.SaveSkuFullReductionRequest
	(*SaveSkuFullReductionResponse)(nil), // 7: proto_spu.SaveSkuFullReductionResponse
	(*SaveSpuBoundsRequest)(nil),         // 8: proto_spu.SaveSpuBoundsRequest
	(*SaveSpuboundsResponse)(nil),        // 9: proto_spu.SaveSpuboundsResponse
	(*SaveMemberPriceRequest)(nil),       // 10: proto_spu.SaveMemberPriceRequest
	(*SaveMemberPriceResponse)(nil),      // 11: proto_spu.SaveMemberPriceResponse
}
var file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_depIdxs = []int32{
	3, // 0: proto_spu.SaveSkuLadderRequest.sku_ladder_entities:type_name -> proto_spu.SkuLadderEntity
	2, // 1: proto_spu.SaveSkuFullReductionRequest.sku_full_reduction_entities:type_name -> proto_spu.SkuFullReductionEntity
	1, // 2: proto_spu.SaveSpuBoundsRequest.spu_bound_entities:type_name -> proto_spu.SpuBoundEntity
	0, // 3: proto_spu.SaveMemberPriceRequest.member_price_entities:type_name -> proto_spu.MemberPriceEntity
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_init() }
func file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_init() {
	if File_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberPriceEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpuBoundEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuFullReductionEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuLadderEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSkuLadderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSkuLadderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSkuFullReductionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSkuFullReductionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSpuBoundsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSpuboundsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveMemberPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveMemberPriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_goTypes,
		DependencyIndexes: file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_depIdxs,
		MessageInfos:      file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_msgTypes,
	}.Build()
	File_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto = out.File
	file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_rawDesc = nil
	file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_goTypes = nil
	file_mall_demo_micro_mall_product_proto_micro_mall_coupon_proto_spu_proto_depIdxs = nil
}
