// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: mall-demo/micro-mall-cart/proto/micro-mall-product-proto/spu.proto

package proto_product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveSpuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuName        string                      `protobuf:"bytes,1,opt,name=spu_name,json=spuName,proto3" json:"spu_name,omitempty"`
	SpuDescription string                      `protobuf:"bytes,2,opt,name=spu_description,json=spuDescription,proto3" json:"spu_description,omitempty"`
	CatalogId      int64                       `protobuf:"varint,3,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`
	BrandId        int64                       `protobuf:"varint,4,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Weight         float64                     `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	PublishStatus  int32                       `protobuf:"varint,6,opt,name=publish_status,json=publishStatus,proto3" json:"publish_status,omitempty"`
	Decript        []string                    `protobuf:"bytes,7,rep,name=decript,proto3" json:"decript,omitempty"`
	Images         []string                    `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	Bounds         *SaveSpuRequest_Bounds      `protobuf:"bytes,9,opt,name=bounds,proto3" json:"bounds,omitempty"`
	BaseAttrs      []*SaveSpuRequest_Baseattrs `protobuf:"bytes,10,rep,name=base_attrs,json=baseAttrs,proto3" json:"base_attrs,omitempty"`
	Skus           []*SaveSpuRequest_Skus      `protobuf:"bytes,11,rep,name=skus,proto3" json:"skus,omitempty"`
}

func (x *SaveSpuRequest) Reset() {
	*x = SaveSpuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSpuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSpuRequest) ProtoMessage() {}

func (x *SaveSpuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSpuRequest.ProtoReflect.Descriptor instead.
func (*SaveSpuRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{0}
}

func (x *SaveSpuRequest) GetSpuName() string {
	if x != nil {
		return x.SpuName
	}
	return ""
}

func (x *SaveSpuRequest) GetSpuDescription() string {
	if x != nil {
		return x.SpuDescription
	}
	return ""
}

func (x *SaveSpuRequest) GetCatalogId() int64 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

func (x *SaveSpuRequest) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *SaveSpuRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SaveSpuRequest) GetPublishStatus() int32 {
	if x != nil {
		return x.PublishStatus
	}
	return 0
}

func (x *SaveSpuRequest) GetDecript() []string {
	if x != nil {
		return x.Decript
	}
	return nil
}

func (x *SaveSpuRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *SaveSpuRequest) GetBounds() *SaveSpuRequest_Bounds {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *SaveSpuRequest) GetBaseAttrs() []*SaveSpuRequest_Baseattrs {
	if x != nil {
		return x.BaseAttrs
	}
	return nil
}

func (x *SaveSpuRequest) GetSkus() []*SaveSpuRequest_Skus {
	if x != nil {
		return x.Skus
	}
	return nil
}

type SaveSpuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveSpuResponse) Reset() {
	*x = SaveSpuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSpuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSpuResponse) ProtoMessage() {}

func (x *SaveSpuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSpuResponse.ProtoReflect.Descriptor instead.
func (*SaveSpuResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{1}
}

type UpSpuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuId int64 `protobuf:"varint,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
}

func (x *UpSpuRequest) Reset() {
	*x = UpSpuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpSpuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpSpuRequest) ProtoMessage() {}

func (x *UpSpuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpSpuRequest.ProtoReflect.Descriptor instead.
func (*UpSpuRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{2}
}

func (x *UpSpuRequest) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

type UpSpuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpSpuResponse) Reset() {
	*x = UpSpuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpSpuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpSpuResponse) ProtoMessage() {}

func (x *UpSpuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpSpuResponse.ProtoReflect.Descriptor instead.
func (*UpSpuResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{3}
}

type SearchSkuInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNum   int32  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`    // 当前页码
	PageSize  int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` //每页记录数
	Keyword   string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`                    //检索关键字
	Order     string `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`                        //排序方式
	Sidx      string `protobuf:"bytes,5,opt,name=sidx,proto3" json:"sidx,omitempty"`                          // 排序字段
	CatelogId int64  `protobuf:"varint,6,opt,name=catelog_id,json=catelogId,proto3" json:"catelog_id,omitempty"`
	BrandId   int64  `protobuf:"varint,7,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Min       int32  `protobuf:"varint,8,opt,name=min,proto3" json:"min,omitempty"`
	Max       int32  `protobuf:"varint,9,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *SearchSkuInfoRequest) Reset() {
	*x = SearchSkuInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchSkuInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSkuInfoRequest) ProtoMessage() {}

func (x *SearchSkuInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSkuInfoRequest.ProtoReflect.Descriptor instead.
func (*SearchSkuInfoRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{4}
}

func (x *SearchSkuInfoRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *SearchSkuInfoRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchSkuInfoRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchSkuInfoRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *SearchSkuInfoRequest) GetSidx() string {
	if x != nil {
		return x.Sidx
	}
	return ""
}

func (x *SearchSkuInfoRequest) GetCatelogId() int64 {
	if x != nil {
		return x.CatelogId
	}
	return 0
}

func (x *SearchSkuInfoRequest) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *SearchSkuInfoRequest) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SearchSkuInfoRequest) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type SearchSkuInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount int32                         `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PageSize   int32                         `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPage  int32                         `protobuf:"varint,3,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	CurrPage   int32                         `protobuf:"varint,4,opt,name=curr_page,json=currPage,proto3" json:"curr_page,omitempty"`
	List       []*SearchSkuInfoResponse_List `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SearchSkuInfoResponse) Reset() {
	*x = SearchSkuInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchSkuInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSkuInfoResponse) ProtoMessage() {}

func (x *SearchSkuInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSkuInfoResponse.ProtoReflect.Descriptor instead.
func (*SearchSkuInfoResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{5}
}

func (x *SearchSkuInfoResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SearchSkuInfoResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchSkuInfoResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *SearchSkuInfoResponse) GetCurrPage() int32 {
	if x != nil {
		return x.CurrPage
	}
	return 0
}

func (x *SearchSkuInfoResponse) GetList() []*SearchSkuInfoResponse_List {
	if x != nil {
		return x.List
	}
	return nil
}

type GetSpuInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuId int64 `protobuf:"varint,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
}

func (x *GetSpuInfoRequest) Reset() {
	*x = GetSpuInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpuInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpuInfoRequest) ProtoMessage() {}

func (x *GetSpuInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpuInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSpuInfoRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{6}
}

func (x *GetSpuInfoRequest) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

type GetSpuInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*GetSpuInfoResponse_Data `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetSpuInfoResponse) Reset() {
	*x = GetSpuInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpuInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpuInfoResponse) ProtoMessage() {}

func (x *GetSpuInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpuInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSpuInfoResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{7}
}

func (x *GetSpuInfoResponse) GetData() []*GetSpuInfoResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateSpuAttrsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuId int64                         `protobuf:"varint,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	Data  []*UpdateSpuAttrsRequest_Data `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateSpuAttrsRequest) Reset() {
	*x = UpdateSpuAttrsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSpuAttrsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpuAttrsRequest) ProtoMessage() {}

func (x *UpdateSpuAttrsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpuAttrsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSpuAttrsRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSpuAttrsRequest) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *UpdateSpuAttrsRequest) GetData() []*UpdateSpuAttrsRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateSpuAttrsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSpuAttrsResponse) Reset() {
	*x = UpdateSpuAttrsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSpuAttrsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpuAttrsResponse) ProtoMessage() {}

func (x *UpdateSpuAttrsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpuAttrsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSpuAttrsResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{9}
}

type SaveSpuRequest_Bounds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuyBounds  int32 `protobuf:"varint,1,opt,name=buy_bounds,json=buyBounds,proto3" json:"buy_bounds,omitempty"`
	GrowBounds int32 `protobuf:"varint,2,opt,name=grow_bounds,json=growBounds,proto3" json:"grow_bounds,omitempty"`
}

func (x *SaveSpuRequest_Bounds) Reset() {
	*x = SaveSpuRequest_Bounds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSpuRequest_Bounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSpuRequest_Bounds) ProtoMessage() {}

func (x *SaveSpuRequest_Bounds) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSpuRequest_Bounds.ProtoReflect.Descriptor instead.
func (*SaveSpuRequest_Bounds) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SaveSpuRequest_Bounds) GetBuyBounds() int32 {
	if x != nil {
		return x.BuyBounds
	}
	return 0
}

func (x *SaveSpuRequest_Bounds) GetGrowBounds() int32 {
	if x != nil {
		return x.GrowBounds
	}
	return 0
}

type SaveSpuRequest_Baseattrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttrId     int32  `protobuf:"varint,1,opt,name=attr_id,json=attrId,proto3" json:"attr_id,omitempty"`
	AttrValues string `protobuf:"bytes,2,opt,name=attr_values,json=attrValues,proto3" json:"attr_values,omitempty"`
	ShowDesc   int32  `protobuf:"varint,3,opt,name=show_desc,json=showDesc,proto3" json:"show_desc,omitempty"`
}

func (x *SaveSpuRequest_Baseattrs) Reset() {
	*x = SaveSpuRequest_Baseattrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSpuRequest_Baseattrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSpuRequest_Baseattrs) ProtoMessage() {}

func (x *SaveSpuRequest_Baseattrs) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSpuRequest_Baseattrs.ProtoReflect.Descriptor instead.
func (*SaveSpuRequest_Baseattrs) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SaveSpuRequest_Baseattrs) GetAttrId() int32 {
	if x != nil {
		return x.AttrId
	}
	return 0
}

func (x *SaveSpuRequest_Baseattrs) GetAttrValues() string {
	if x != nil {
		return x.AttrValues
	}
	return ""
}

func (x *SaveSpuRequest_Baseattrs) GetShowDesc() int32 {
	if x != nil {
		return x.ShowDesc
	}
	return 0
}

type SaveSpuRequest_Attr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttrId    int32  `protobuf:"varint,1,opt,name=attr_id,json=attrId,proto3" json:"attr_id,omitempty"`
	AttrName  string `protobuf:"bytes,2,opt,name=attr_name,json=attrName,proto3" json:"attr_name,omitempty"`
	AttrValue string `protobuf:"bytes,3,opt,name=attr_value,json=attrValue,proto3" json:"attr_value,omitempty"`
}

func (x *SaveSpuRequest_Attr) Reset() {
	*x = SaveSpuRequest_Attr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSpuRequest_Attr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSpuRequest_Attr) ProtoMessage() {}

func (x *SaveSpuRequest_Attr) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSpuRequest_Attr.ProtoReflect.Descriptor instead.
func (*SaveSpuRequest_Attr) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{0, 2}
}

func (x *SaveSpuRequest_Attr) GetAttrId() int32 {
	if x != nil {
		return x.AttrId
	}
	return 0
}

func (x *SaveSpuRequest_Attr) GetAttrName() string {
	if x != nil {
		return x.AttrName
	}
	return ""
}

func (x *SaveSpuRequest_Attr) GetAttrValue() string {
	if x != nil {
		return x.AttrValue
	}
	return ""
}

type SaveSpuRequest_Images struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImgUrl     string `protobuf:"bytes,1,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	DefaultTmg int32  `protobuf:"varint,2,opt,name=default_tmg,json=defaultTmg,proto3" json:"default_tmg,omitempty"`
}

func (x *SaveSpuRequest_Images) Reset() {
	*x = SaveSpuRequest_Images{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSpuRequest_Images) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSpuRequest_Images) ProtoMessage() {}

func (x *SaveSpuRequest_Images) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSpuRequest_Images.ProtoReflect.Descriptor instead.
func (*SaveSpuRequest_Images) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{0, 3}
}

func (x *SaveSpuRequest_Images) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *SaveSpuRequest_Images) GetDefaultTmg() int32 {
	if x != nil {
		return x.DefaultTmg
	}
	return 0
}

type SaveSpuRequest_Memberprice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *SaveSpuRequest_Memberprice) Reset() {
	*x = SaveSpuRequest_Memberprice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSpuRequest_Memberprice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSpuRequest_Memberprice) ProtoMessage() {}

func (x *SaveSpuRequest_Memberprice) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSpuRequest_Memberprice.ProtoReflect.Descriptor instead.
func (*SaveSpuRequest_Memberprice) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{0, 4}
}

func (x *SaveSpuRequest_Memberprice) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveSpuRequest_Memberprice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveSpuRequest_Memberprice) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type SaveSpuRequest_Skus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attr        []*SaveSpuRequest_Attr        `protobuf:"bytes,1,rep,name=attr,proto3" json:"attr,omitempty"`
	SkuName     string                        `protobuf:"bytes,2,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	Price       float64                       `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	SkuTitle    string                        `protobuf:"bytes,4,opt,name=sku_title,json=skuTitle,proto3" json:"sku_title,omitempty"`
	SkuSubtitle string                        `protobuf:"bytes,5,opt,name=sku_subtitle,json=skuSubtitle,proto3" json:"sku_subtitle,omitempty"`
	Images      []*SaveSpuRequest_Images      `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	Descar      []string                      `protobuf:"bytes,7,rep,name=descar,proto3" json:"descar,omitempty"`
	FullCount   int32                         `protobuf:"varint,8,opt,name=full_count,json=fullCount,proto3" json:"full_count,omitempty"`
	Discount    float64                       `protobuf:"fixed64,9,opt,name=discount,proto3" json:"discount,omitempty"`
	CountStatus int32                         `protobuf:"varint,10,opt,name=count_status,json=countStatus,proto3" json:"count_status,omitempty"`
	FullPrice   int32                         `protobuf:"varint,11,opt,name=full_price,json=fullPrice,proto3" json:"full_price,omitempty"`
	ReducePrice int32                         `protobuf:"varint,12,opt,name=reduce_price,json=reducePrice,proto3" json:"reduce_price,omitempty"`
	PriceStatus int32                         `protobuf:"varint,13,opt,name=price_status,json=priceStatus,proto3" json:"price_status,omitempty"`
	MemberPrice []*SaveSpuRequest_Memberprice `protobuf:"bytes,14,rep,name=member_price,json=memberPrice,proto3" json:"member_price,omitempty"`
}

func (x *SaveSpuRequest_Skus) Reset() {
	*x = SaveSpuRequest_Skus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSpuRequest_Skus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSpuRequest_Skus) ProtoMessage() {}

func (x *SaveSpuRequest_Skus) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSpuRequest_Skus.ProtoReflect.Descriptor instead.
func (*SaveSpuRequest_Skus) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{0, 5}
}

func (x *SaveSpuRequest_Skus) GetAttr() []*SaveSpuRequest_Attr {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *SaveSpuRequest_Skus) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *SaveSpuRequest_Skus) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SaveSpuRequest_Skus) GetSkuTitle() string {
	if x != nil {
		return x.SkuTitle
	}
	return ""
}

func (x *SaveSpuRequest_Skus) GetSkuSubtitle() string {
	if x != nil {
		return x.SkuSubtitle
	}
	return ""
}

func (x *SaveSpuRequest_Skus) GetImages() []*SaveSpuRequest_Images {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *SaveSpuRequest_Skus) GetDescar() []string {
	if x != nil {
		return x.Descar
	}
	return nil
}

func (x *SaveSpuRequest_Skus) GetFullCount() int32 {
	if x != nil {
		return x.FullCount
	}
	return 0
}

func (x *SaveSpuRequest_Skus) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *SaveSpuRequest_Skus) GetCountStatus() int32 {
	if x != nil {
		return x.CountStatus
	}
	return 0
}

func (x *SaveSpuRequest_Skus) GetFullPrice() int32 {
	if x != nil {
		return x.FullPrice
	}
	return 0
}

func (x *SaveSpuRequest_Skus) GetReducePrice() int32 {
	if x != nil {
		return x.ReducePrice
	}
	return 0
}

func (x *SaveSpuRequest_Skus) GetPriceStatus() int32 {
	if x != nil {
		return x.PriceStatus
	}
	return 0
}

func (x *SaveSpuRequest_Skus) GetMemberPrice() []*SaveSpuRequest_Memberprice {
	if x != nil {
		return x.MemberPrice
	}
	return nil
}

type SearchSkuInfoResponse_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId         uint32  `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SpuId         uint32  `protobuf:"varint,2,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	SkuName       string  `protobuf:"bytes,3,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	SkuDesc       string  `protobuf:"bytes,4,opt,name=sku_desc,json=skuDesc,proto3" json:"sku_desc,omitempty"`
	CatalogId     uint32  `protobuf:"varint,5,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`
	BrandId       uint32  `protobuf:"varint,6,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	SkuDefaultImg string  `protobuf:"bytes,7,opt,name=sku_default_img,json=skuDefaultImg,proto3" json:"sku_default_img,omitempty"`
	SkuTitle      string  `protobuf:"bytes,8,opt,name=sku_title,json=skuTitle,proto3" json:"sku_title,omitempty"`
	SkuSubtitle   string  `protobuf:"bytes,9,opt,name=sku_subtitle,json=skuSubtitle,proto3" json:"sku_subtitle,omitempty"`
	Price         float64 `protobuf:"fixed64,10,opt,name=price,proto3" json:"price,omitempty"`
	SaleCount     uint32  `protobuf:"varint,11,opt,name=sale_count,json=saleCount,proto3" json:"sale_count,omitempty"`
}

func (x *SearchSkuInfoResponse_List) Reset() {
	*x = SearchSkuInfoResponse_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchSkuInfoResponse_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSkuInfoResponse_List) ProtoMessage() {}

func (x *SearchSkuInfoResponse_List) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSkuInfoResponse_List.ProtoReflect.Descriptor instead.
func (*SearchSkuInfoResponse_List) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SearchSkuInfoResponse_List) GetSkuId() uint32 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *SearchSkuInfoResponse_List) GetSpuId() uint32 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *SearchSkuInfoResponse_List) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *SearchSkuInfoResponse_List) GetSkuDesc() string {
	if x != nil {
		return x.SkuDesc
	}
	return ""
}

func (x *SearchSkuInfoResponse_List) GetCatalogId() uint32 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

func (x *SearchSkuInfoResponse_List) GetBrandId() uint32 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *SearchSkuInfoResponse_List) GetSkuDefaultImg() string {
	if x != nil {
		return x.SkuDefaultImg
	}
	return ""
}

func (x *SearchSkuInfoResponse_List) GetSkuTitle() string {
	if x != nil {
		return x.SkuTitle
	}
	return ""
}

func (x *SearchSkuInfoResponse_List) GetSkuSubtitle() string {
	if x != nil {
		return x.SkuSubtitle
	}
	return ""
}

func (x *SearchSkuInfoResponse_List) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SearchSkuInfoResponse_List) GetSaleCount() uint32 {
	if x != nil {
		return x.SaleCount
	}
	return 0
}

type GetSpuInfoResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SpuId     uint32 `protobuf:"varint,2,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	AttrId    uint32 `protobuf:"varint,3,opt,name=attr_id,json=attrId,proto3" json:"attr_id,omitempty"`
	AttrName  string `protobuf:"bytes,4,opt,name=attr_name,json=attrName,proto3" json:"attr_name,omitempty"`
	AttrValue string `protobuf:"bytes,5,opt,name=attr_value,json=attrValue,proto3" json:"attr_value,omitempty"`
	AttrSort  string `protobuf:"bytes,6,opt,name=attr_sort,json=attrSort,proto3" json:"attr_sort,omitempty"`
	QuickShow uint32 `protobuf:"varint,7,opt,name=quick_show,json=quickShow,proto3" json:"quick_show,omitempty"`
}

func (x *GetSpuInfoResponse_Data) Reset() {
	*x = GetSpuInfoResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpuInfoResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpuInfoResponse_Data) ProtoMessage() {}

func (x *GetSpuInfoResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpuInfoResponse_Data.ProtoReflect.Descriptor instead.
func (*GetSpuInfoResponse_Data) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetSpuInfoResponse_Data) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetSpuInfoResponse_Data) GetSpuId() uint32 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *GetSpuInfoResponse_Data) GetAttrId() uint32 {
	if x != nil {
		return x.AttrId
	}
	return 0
}

func (x *GetSpuInfoResponse_Data) GetAttrName() string {
	if x != nil {
		return x.AttrName
	}
	return ""
}

func (x *GetSpuInfoResponse_Data) GetAttrValue() string {
	if x != nil {
		return x.AttrValue
	}
	return ""
}

func (x *GetSpuInfoResponse_Data) GetAttrSort() string {
	if x != nil {
		return x.AttrSort
	}
	return ""
}

func (x *GetSpuInfoResponse_Data) GetQuickShow() uint32 {
	if x != nil {
		return x.QuickShow
	}
	return 0
}

type UpdateSpuAttrsRequest_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SpuId     uint32 `protobuf:"varint,2,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	AttrId    uint32 `protobuf:"varint,3,opt,name=attr_id,json=attrId,proto3" json:"attr_id,omitempty"`
	AttrName  string `protobuf:"bytes,4,opt,name=attr_name,json=attrName,proto3" json:"attr_name,omitempty"`
	AttrValue string `protobuf:"bytes,5,opt,name=attr_value,json=attrValue,proto3" json:"attr_value,omitempty"`
	AttrSort  string `protobuf:"bytes,6,opt,name=attr_sort,json=attrSort,proto3" json:"attr_sort,omitempty"`
	QuickShow uint32 `protobuf:"varint,7,opt,name=quick_show,json=quickShow,proto3" json:"quick_show,omitempty"`
}

func (x *UpdateSpuAttrsRequest_Data) Reset() {
	*x = UpdateSpuAttrsRequest_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSpuAttrsRequest_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpuAttrsRequest_Data) ProtoMessage() {}

func (x *UpdateSpuAttrsRequest_Data) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpuAttrsRequest_Data.ProtoReflect.Descriptor instead.
func (*UpdateSpuAttrsRequest_Data) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP(), []int{8, 0}
}

func (x *UpdateSpuAttrsRequest_Data) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSpuAttrsRequest_Data) GetSpuId() uint32 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *UpdateSpuAttrsRequest_Data) GetAttrId() uint32 {
	if x != nil {
		return x.AttrId
	}
	return 0
}

func (x *UpdateSpuAttrsRequest_Data) GetAttrName() string {
	if x != nil {
		return x.AttrName
	}
	return ""
}

func (x *UpdateSpuAttrsRequest_Data) GetAttrValue() string {
	if x != nil {
		return x.AttrValue
	}
	return ""
}

func (x *UpdateSpuAttrsRequest_Data) GetAttrSort() string {
	if x != nil {
		return x.AttrSort
	}
	return ""
}

func (x *UpdateSpuAttrsRequest_Data) GetQuickShow() uint32 {
	if x != nil {
		return x.QuickShow
	}
	return 0
}

var File_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto protoreflect.FileDescriptor

var file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDesc = []byte{
	0x0a, 0x42, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2d, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2d, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x75, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x70, 0x75, 0x22,
	0xd6, 0x0a, 0x0a, 0x0e, 0x53, 0x61, 0x76, 0x65, 0x53, 0x70, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x75, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x73, 0x70, 0x75, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x70, 0x75, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x64, 0x65, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x38, 0x0a, 0x06, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x70, 0x75, 0x2e, 0x53, 0x61,
	0x76, 0x65, 0x53, 0x70, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x6f, 0x75,
	0x6e, 0x64, 0x73, 0x52, 0x06, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x42, 0x0a, 0x0a, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x70, 0x75, 0x2e, 0x53, 0x61, 0x76, 0x65,
	0x53, 0x70, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x61,
	0x74, 0x74, 0x72, 0x73, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73, 0x12,
	0x32, 0x0a, 0x04, 0x73, 0x6b, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x70, 0x75, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x53, 0x70,
	0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6b, 0x75, 0x73, 0x52, 0x04, 0x73,
	0x6b, 0x75, 0x73, 0x1a, 0x48, 0x0a, 0x06, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x75, 0x79, 0x5f, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x62, 0x75, 0x79, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x67, 0x72, 0x6f, 0x77, 0x5f, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x67, 0x72, 0x6f, 0x77, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x1a, 0x62, 0x0a,
	0x09, 0x42, 0x61, 0x73, 0x65, 0x61, 0x74, 0x74, 0x72, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x74,
	0x74, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x74, 0x74,
	0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x64, 0x65, 0x73,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x77, 0x44, 0x65, 0x73,
	0x63, 0x1a, 0x5b, 0x0a, 0x04, 0x41, 0x74, 0x74, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x74, 0x74,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x74, 0x74, 0x72,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x74, 0x74, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x42,
	0x0a, 0x06, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6d, 0x67, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x72,
	0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x74, 0x6d, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54,
	0x6d, 0x67, 0x1a, 0x47, 0x0a, 0x0b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x1a, 0x8a, 0x04, 0x0a, 0x04,
	0x53, 0x6b, 0x75, 0x73, 0x12, 0x32, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x70, 0x75, 0x2e, 0x53,
	0x61, 0x76, 0x65, 0x53, 0x70, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x74,
	0x74, 0x72, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x75, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x75, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6b, 0x75,
	0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6b,
	0x75, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x6b, 0x75, 0x5f, 0x73, 0x75,
	0x62, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x6b,
	0x75, 0x53, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x73, 0x70, 0x75, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x53, 0x70, 0x75, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x52, 0x06, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x73, 0x63, 0x61, 0x72, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x73, 0x63, 0x61, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x66,
	0x75, 0x6c, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x66, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x75, 0x6c,
	0x6c, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66,
	0x75, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x48,
	0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0e,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x70, 0x75,
	0x2e, 0x53, 0x61, 0x76, 0x65, 0x53, 0x70, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x70, 0x72, 0x69, 0x63, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x61, 0x76, 0x65,
	0x53, 0x70, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x0a, 0x0c, 0x55,
	0x70, 0x53, 0x70, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x73,
	0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x70, 0x75,
	0x49, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x70, 0x53, 0x70, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0xf0, 0x01, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x6b,
	0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x78, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x64, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65,
	0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x61,
	0x74, 0x65, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x72, 0x61, 0x6e, 0x64,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x90, 0x04, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x75, 0x72, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x73, 0x70, 0x75, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x6b, 0x75, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0xc1, 0x02, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15,
	0x0a, 0x06, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x73, 0x6b, 0x75, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x70, 0x75, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x73, 0x6b, 0x75, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x6b, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x75, 0x5f, 0x64,
	0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x75, 0x44, 0x65,
	0x73, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f,
	0x73, 0x6b, 0x75, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x69, 0x6d, 0x67, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x6b, 0x75, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x49, 0x6d, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6b, 0x75, 0x5f, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6b, 0x75, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x6b, 0x75, 0x5f, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x6b, 0x75, 0x53, 0x75, 0x62, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61,
	0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x73, 0x61, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2a, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15,
	0x0a, 0x06, 0x73, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x73, 0x70, 0x75, 0x49, 0x64, 0x22, 0x8d, 0x02, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x70, 0x75,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x73, 0x70, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0xbe, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x73, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x70, 0x75, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x74, 0x74, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x74, 0x74, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74,
	0x74, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x74, 0x74,
	0x72, 0x5f, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x74,
	0x74, 0x72, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x5f,
	0x73, 0x68, 0x6f, 0x77, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x71, 0x75, 0x69, 0x63,
	0x6b, 0x53, 0x68, 0x6f, 0x77, 0x22, 0xaa, 0x02, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x70, 0x75, 0x41, 0x74, 0x74, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x15, 0x0a, 0x06, 0x73, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x73, 0x70, 0x75, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x70, 0x75,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x70, 0x75, 0x41, 0x74, 0x74, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0xbe, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x70,
	0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x70, 0x75, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x61, 0x74, 0x74, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x74,
	0x74, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61,
	0x74, 0x74, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x74,
	0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x73,
	0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x74, 0x74, 0x72, 0x53,
	0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x5f, 0x73, 0x68, 0x6f,
	0x77, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x53, 0x68,
	0x6f, 0x77, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x70, 0x75, 0x41,
	0x74, 0x74, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescOnce sync.Once
	file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescData = file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDesc
)

func file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescGZIP() []byte {
	file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescOnce.Do(func() {
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescData = protoimpl.X.CompressGZIP(file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescData)
	})
	return file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDescData
}

var file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_goTypes = []interface{}{
	(*SaveSpuRequest)(nil),             // 0: proto_spu.SaveSpuRequest
	(*SaveSpuResponse)(nil),            // 1: proto_spu.SaveSpuResponse
	(*UpSpuRequest)(nil),               // 2: proto_spu.UpSpuRequest
	(*UpSpuResponse)(nil),              // 3: proto_spu.UpSpuResponse
	(*SearchSkuInfoRequest)(nil),       // 4: proto_spu.SearchSkuInfoRequest
	(*SearchSkuInfoResponse)(nil),      // 5: proto_spu.SearchSkuInfoResponse
	(*GetSpuInfoRequest)(nil),          // 6: proto_spu.GetSpuInfoRequest
	(*GetSpuInfoResponse)(nil),         // 7: proto_spu.GetSpuInfoResponse
	(*UpdateSpuAttrsRequest)(nil),      // 8: proto_spu.UpdateSpuAttrsRequest
	(*UpdateSpuAttrsResponse)(nil),     // 9: proto_spu.UpdateSpuAttrsResponse
	(*SaveSpuRequest_Bounds)(nil),      // 10: proto_spu.SaveSpuRequest.Bounds
	(*SaveSpuRequest_Baseattrs)(nil),   // 11: proto_spu.SaveSpuRequest.Baseattrs
	(*SaveSpuRequest_Attr)(nil),        // 12: proto_spu.SaveSpuRequest.Attr
	(*SaveSpuRequest_Images)(nil),      // 13: proto_spu.SaveSpuRequest.Images
	(*SaveSpuRequest_Memberprice)(nil), // 14: proto_spu.SaveSpuRequest.Memberprice
	(*SaveSpuRequest_Skus)(nil),        // 15: proto_spu.SaveSpuRequest.Skus
	(*SearchSkuInfoResponse_List)(nil), // 16: proto_spu.SearchSkuInfoResponse.List
	(*GetSpuInfoResponse_Data)(nil),    // 17: proto_spu.GetSpuInfoResponse.Data
	(*UpdateSpuAttrsRequest_Data)(nil), // 18: proto_spu.UpdateSpuAttrsRequest.Data
}
var file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_depIdxs = []int32{
	10, // 0: proto_spu.SaveSpuRequest.bounds:type_name -> proto_spu.SaveSpuRequest.Bounds
	11, // 1: proto_spu.SaveSpuRequest.base_attrs:type_name -> proto_spu.SaveSpuRequest.Baseattrs
	15, // 2: proto_spu.SaveSpuRequest.skus:type_name -> proto_spu.SaveSpuRequest.Skus
	16, // 3: proto_spu.SearchSkuInfoResponse.list:type_name -> proto_spu.SearchSkuInfoResponse.List
	17, // 4: proto_spu.GetSpuInfoResponse.data:type_name -> proto_spu.GetSpuInfoResponse.Data
	18, // 5: proto_spu.UpdateSpuAttrsRequest.data:type_name -> proto_spu.UpdateSpuAttrsRequest.Data
	12, // 6: proto_spu.SaveSpuRequest.Skus.attr:type_name -> proto_spu.SaveSpuRequest.Attr
	13, // 7: proto_spu.SaveSpuRequest.Skus.images:type_name -> proto_spu.SaveSpuRequest.Images
	14, // 8: proto_spu.SaveSpuRequest.Skus.member_price:type_name -> proto_spu.SaveSpuRequest.Memberprice
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_init() }
func file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_init() {
	if File_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSpuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSpuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpSpuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpSpuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchSkuInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchSkuInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpuInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpuInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSpuAttrsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSpuAttrsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSpuRequest_Bounds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSpuRequest_Baseattrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSpuRequest_Attr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSpuRequest_Images); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSpuRequest_Memberprice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSpuRequest_Skus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchSkuInfoResponse_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpuInfoResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSpuAttrsRequest_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_goTypes,
		DependencyIndexes: file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_depIdxs,
		MessageInfos:      file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_msgTypes,
	}.Build()
	File_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto = out.File
	file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_rawDesc = nil
	file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_goTypes = nil
	file_mall_demo_micro_mall_cart_proto_micro_mall_product_proto_spu_proto_depIdxs = nil
}
