// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: mall-demo/micro-mall-order/proto/micro-mall-order-proto/order.proto

package proto_order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto protoreflect.FileDescriptor

var file_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto_rawDesc = []byte{
	0x0a, 0x43, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2d, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2d, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x0a, 0x0a, 0x08,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x70, 0x63, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto_goTypes = []interface{}{}
var file_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto_init() }
func file_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto_init() {
	if File_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto_goTypes,
		DependencyIndexes: file_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto_depIdxs,
	}.Build()
	File_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto = out.File
	file_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto_rawDesc = nil
	file_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto_goTypes = nil
	file_mall_demo_micro_mall_order_proto_micro_mall_order_proto_order_proto_depIdxs = nil
}
