// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: mall-demo/micro-mall-order/proto/micro-mall-order-proto/order.proto

package proto_order

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderRpcClient is the client API for OrderRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderRpcClient interface {
}

type orderRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderRpcClient(cc grpc.ClientConnInterface) OrderRpcClient {
	return &orderRpcClient{cc}
}

// OrderRpcServer is the server API for OrderRpc service.
// All implementations must embed UnimplementedOrderRpcServer
// for forward compatibility
type OrderRpcServer interface {
	mustEmbedUnimplementedOrderRpcServer()
}

// UnimplementedOrderRpcServer must be embedded to have forward compatible implementations.
type UnimplementedOrderRpcServer struct {
}

func (UnimplementedOrderRpcServer) mustEmbedUnimplementedOrderRpcServer() {}

// UnsafeOrderRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderRpcServer will
// result in compilation errors.
type UnsafeOrderRpcServer interface {
	mustEmbedUnimplementedOrderRpcServer()
}

func RegisterOrderRpcServer(s grpc.ServiceRegistrar, srv OrderRpcServer) {
	s.RegisterService(&OrderRpc_ServiceDesc, srv)
}

// OrderRpc_ServiceDesc is the grpc.ServiceDesc for OrderRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OrderRpc",
	HandlerType: (*OrderRpcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "mall-demo/micro-mall-order/proto/micro-mall-order-proto/order.proto",
}
