// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: mall-demo/micro-mall-search/proto/micro-mall-search-proto/search.proto

package proto_search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductStatusUpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities []*ProductStatusUpRequest_Entity `protobuf:"bytes,13,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *ProductStatusUpRequest) Reset() {
	*x = ProductStatusUpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductStatusUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStatusUpRequest) ProtoMessage() {}

func (x *ProductStatusUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStatusUpRequest.ProtoReflect.Descriptor instead.
func (*ProductStatusUpRequest) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDescGZIP(), []int{0}
}

func (x *ProductStatusUpRequest) GetEntities() []*ProductStatusUpRequest_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type ProductStatusUpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProductStatusUpResponse) Reset() {
	*x = ProductStatusUpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductStatusUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStatusUpResponse) ProtoMessage() {}

func (x *ProductStatusUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStatusUpResponse.ProtoReflect.Descriptor instead.
func (*ProductStatusUpResponse) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDescGZIP(), []int{1}
}

type ProductStatusUpRequest_Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId       int64                                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SpuId       int64                                 `protobuf:"varint,2,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	SkuTitle    string                                `protobuf:"bytes,3,opt,name=sku_title,json=skuTitle,proto3" json:"sku_title,omitempty"`
	SkuPrice    float64                               `protobuf:"fixed64,4,opt,name=sku_price,json=skuPrice,proto3" json:"sku_price,omitempty"`
	SaleCount   int64                                 `protobuf:"varint,5,opt,name=sale_count,json=saleCount,proto3" json:"sale_count,omitempty"`
	HasStock    bool                                  `protobuf:"varint,6,opt,name=has_stock,json=hasStock,proto3" json:"has_stock,omitempty"`
	BrandId     int64                                 `protobuf:"varint,7,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	CatalogId   int64                                 `protobuf:"varint,8,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`
	BrandName   string                                `protobuf:"bytes,9,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	BrandImg    string                                `protobuf:"bytes,10,opt,name=brand_img,json=brandImg,proto3" json:"brand_img,omitempty"`
	CatalogName string                                `protobuf:"bytes,11,opt,name=catalog_name,json=catalogName,proto3" json:"catalog_name,omitempty"`
	HotScore    int64                                 `protobuf:"varint,12,opt,name=hot_score,json=hotScore,proto3" json:"hot_score,omitempty"`
	Attrs       []*ProductStatusUpRequest_Entity_Attr `protobuf:"bytes,13,rep,name=attrs,proto3" json:"attrs,omitempty"`
}

func (x *ProductStatusUpRequest_Entity) Reset() {
	*x = ProductStatusUpRequest_Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductStatusUpRequest_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStatusUpRequest_Entity) ProtoMessage() {}

func (x *ProductStatusUpRequest_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStatusUpRequest_Entity.ProtoReflect.Descriptor instead.
func (*ProductStatusUpRequest_Entity) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProductStatusUpRequest_Entity) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *ProductStatusUpRequest_Entity) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *ProductStatusUpRequest_Entity) GetSkuTitle() string {
	if x != nil {
		return x.SkuTitle
	}
	return ""
}

func (x *ProductStatusUpRequest_Entity) GetSkuPrice() float64 {
	if x != nil {
		return x.SkuPrice
	}
	return 0
}

func (x *ProductStatusUpRequest_Entity) GetSaleCount() int64 {
	if x != nil {
		return x.SaleCount
	}
	return 0
}

func (x *ProductStatusUpRequest_Entity) GetHasStock() bool {
	if x != nil {
		return x.HasStock
	}
	return false
}

func (x *ProductStatusUpRequest_Entity) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *ProductStatusUpRequest_Entity) GetCatalogId() int64 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

func (x *ProductStatusUpRequest_Entity) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *ProductStatusUpRequest_Entity) GetBrandImg() string {
	if x != nil {
		return x.BrandImg
	}
	return ""
}

func (x *ProductStatusUpRequest_Entity) GetCatalogName() string {
	if x != nil {
		return x.CatalogName
	}
	return ""
}

func (x *ProductStatusUpRequest_Entity) GetHotScore() int64 {
	if x != nil {
		return x.HotScore
	}
	return 0
}

func (x *ProductStatusUpRequest_Entity) GetAttrs() []*ProductStatusUpRequest_Entity_Attr {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type ProductStatusUpRequest_Entity_Attr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttrId    int64  `protobuf:"varint,1,opt,name=attr_id,json=attrId,proto3" json:"attr_id,omitempty"`
	AttrName  string `protobuf:"bytes,2,opt,name=attr_name,json=attrName,proto3" json:"attr_name,omitempty"`
	AttrValue string `protobuf:"bytes,3,opt,name=attr_value,json=attrValue,proto3" json:"attr_value,omitempty"`
}

func (x *ProductStatusUpRequest_Entity_Attr) Reset() {
	*x = ProductStatusUpRequest_Entity_Attr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductStatusUpRequest_Entity_Attr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStatusUpRequest_Entity_Attr) ProtoMessage() {}

func (x *ProductStatusUpRequest_Entity_Attr) ProtoReflect() protoreflect.Message {
	mi := &file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStatusUpRequest_Entity_Attr.ProtoReflect.Descriptor instead.
func (*ProductStatusUpRequest_Entity_Attr) Descriptor() ([]byte, []int) {
	return file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ProductStatusUpRequest_Entity_Attr) GetAttrId() int64 {
	if x != nil {
		return x.AttrId
	}
	return 0
}

func (x *ProductStatusUpRequest_Entity_Attr) GetAttrName() string {
	if x != nil {
		return x.AttrName
	}
	return ""
}

func (x *ProductStatusUpRequest_Entity_Attr) GetAttrValue() string {
	if x != nil {
		return x.AttrValue
	}
	return ""
}

var File_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto protoreflect.FileDescriptor

var file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDesc = []byte{
	0x0a, 0x46, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2d, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2d, 0x6d, 0x61, 0x6c, 0x6c, 0x2d, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x22, 0xdf, 0x04, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x08, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x81,
	0x04, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x6b, 0x75,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x6b, 0x75, 0x49, 0x64,
	0x12, 0x15, 0x0a, 0x06, 0x73, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x73, 0x70, 0x75, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6b, 0x75, 0x5f, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6b, 0x75, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6b, 0x75, 0x5f, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x73, 0x6b, 0x75, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x61, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61, 0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x19, 0x0a,
	0x08, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x61,
	0x74, 0x61, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x72, 0x61, 0x6e, 0x64,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x72, 0x61,
	0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x5f,
	0x69, 0x6d, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x64,
	0x49, 0x6d, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x74, 0x5f, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x68, 0x6f, 0x74, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x40, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x0d, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x52, 0x05,
	0x61, 0x74, 0x74, 0x72, 0x73, 0x1a, 0x5b, 0x0a, 0x04, 0x41, 0x74, 0x74, 0x72, 0x12, 0x17, 0x0a,
	0x07, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x61, 0x74, 0x74, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x74, 0x74, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x55, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x5f, 0x0a,
	0x09, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x70, 0x63, 0x12, 0x52, 0x0a, 0x0f, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x12, 0x1e, 0x2e,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f,
	0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDescOnce sync.Once
	file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDescData = file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDesc
)

func file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDescGZIP() []byte {
	file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDescOnce.Do(func() {
		file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDescData = protoimpl.X.CompressGZIP(file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDescData)
	})
	return file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDescData
}

var file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_goTypes = []interface{}{
	(*ProductStatusUpRequest)(nil),             // 0: search.ProductStatusUpRequest
	(*ProductStatusUpResponse)(nil),            // 1: search.ProductStatusUpResponse
	(*ProductStatusUpRequest_Entity)(nil),      // 2: search.ProductStatusUpRequest.Entity
	(*ProductStatusUpRequest_Entity_Attr)(nil), // 3: search.ProductStatusUpRequest.Entity.Attr
}
var file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_depIdxs = []int32{
	2, // 0: search.ProductStatusUpRequest.entities:type_name -> search.ProductStatusUpRequest.Entity
	3, // 1: search.ProductStatusUpRequest.Entity.attrs:type_name -> search.ProductStatusUpRequest.Entity.Attr
	0, // 2: search.SearchRpc.ProductStatusUp:input_type -> search.ProductStatusUpRequest
	1, // 3: search.SearchRpc.ProductStatusUp:output_type -> search.ProductStatusUpResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_init() }
func file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_init() {
	if File_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductStatusUpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductStatusUpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductStatusUpRequest_Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductStatusUpRequest_Entity_Attr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_goTypes,
		DependencyIndexes: file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_depIdxs,
		MessageInfos:      file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_msgTypes,
	}.Build()
	File_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto = out.File
	file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_rawDesc = nil
	file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_goTypes = nil
	file_mall_demo_micro_mall_search_proto_micro_mall_search_proto_search_proto_depIdxs = nil
}
